package main

import (
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	// generated by protoc-gen-go
	"example/cmd/server/adapters"
	"example/gen/album/v1/albumv1connect" // generated by protoc-gen-connect-go
)

func main() {
	albumServer := &adapters.AlbumServer{}
	albumServer.Init()
	mux := http.NewServeMux()
	path, handler := albumv1connect.NewAlbumServiceHandler(albumServer)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
